// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Support.Persistence.Contexts;

namespace TechnicalAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210515024211_Elimino registros")]
    partial class Eliminoregistros
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Support.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5ba9d9e8-9d02-4cda-ac87-35416b3ea0e9"),
                            password = "juan123",
                            username = "Juan"
                        },
                        new
                        {
                            Id = new Guid("c0557d72-7971-492b-8831-6b64a8b6d622"),
                            password = "lucrecia123",
                            username = "Lucrecia"
                        },
                        new
                        {
                            Id = new Guid("a3a3df4d-b7e0-40f8-ba0d-271176632f4f"),
                            password = "maria123",
                            username = "Maria"
                        },
                        new
                        {
                            Id = new Guid("6cb6a1f0-a618-4afb-8758-8ed054e3f7ab"),
                            password = "esteban123",
                            username = "Esteban"
                        },
                        new
                        {
                            Id = new Guid("1df0936d-a651-4c4d-a04f-ce9fc0cf1492"),
                            password = "pilar123",
                            username = "Pilar"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
