// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Support.Persistence.Contexts;

namespace TechnicalAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210515025646_Agrego datos a la tabla User")]
    partial class AgregodatosalatablaUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Support.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("547500a4-81ff-4524-9240-e929dd4c01e0"),
                            password = "juan123",
                            username = "Juan"
                        },
                        new
                        {
                            Id = new Guid("ae5c8d37-290e-41e8-a926-6346857c3a20"),
                            password = "lucrecia123",
                            username = "Lucrecia"
                        },
                        new
                        {
                            Id = new Guid("3281a131-f730-4653-a9b1-30511f4ed97c"),
                            password = "maria123",
                            username = "Maria"
                        },
                        new
                        {
                            Id = new Guid("cf35a1f9-928d-4700-a4a8-c483e29e90c0"),
                            password = "esteban123",
                            username = "Esteban"
                        },
                        new
                        {
                            Id = new Guid("c59f5b8a-1e1d-45d0-b81f-f65b62a61ade"),
                            password = "pilar123",
                            username = "Pilar"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
