// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Support.Persistence.Contexts;

namespace TechnicalAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210512040250_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Support.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c87b48b6-0b13-4093-b188-9d3f4855416a"),
                            email = "juan@juan.com",
                            username = "Juan"
                        },
                        new
                        {
                            Id = new Guid("d2b05267-837d-4f70-b3f7-5ef878581202"),
                            email = "lucrecia@lucrecia.com",
                            username = "Lucrecia"
                        },
                        new
                        {
                            Id = new Guid("a460de80-0626-4ede-9124-3a5c1291e8d1"),
                            email = "maria@maria.com",
                            username = "Maria"
                        },
                        new
                        {
                            Id = new Guid("94b38084-71bb-463c-9415-03a90d17aaa8"),
                            email = "esteban@esteban.com",
                            username = "Esteban"
                        },
                        new
                        {
                            Id = new Guid("e9c36979-8fc4-4827-a60d-eadbb1d8ffb1"),
                            email = "pilar@pilar.com",
                            username = "Pilar"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
