// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Support.Persistence.Contexts;

namespace TechnicalAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210515024759_Modifico modelo de datos de User")]
    partial class ModificomodelodedatosdeUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Support.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1e18b90a-2ba2-4f96-87b0-5cd3cd1c3e93"),
                            password = "juan123",
                            username = "Juan"
                        },
                        new
                        {
                            Id = new Guid("2b278e05-4684-4e48-9eee-d493f1fcdf5c"),
                            password = "lucrecia123",
                            username = "Lucrecia"
                        },
                        new
                        {
                            Id = new Guid("34cc03fa-879c-4cba-8354-8e6741ef6126"),
                            password = "maria123",
                            username = "Maria"
                        },
                        new
                        {
                            Id = new Guid("6fc43413-a00e-4ea0-b4de-50c29342d672"),
                            password = "esteban123",
                            username = "Esteban"
                        },
                        new
                        {
                            Id = new Guid("bd1f5b2f-2413-48b5-bd4f-166a716d7bf2"),
                            password = "pilar123",
                            username = "Pilar"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
